// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Internal Build 593 12/11/2017)
// Created on Fri Dec 08 19:38:40 2023

ALU ALU_inst
(
	.X(X_sig) ,	// input [31:0] X_sig
	.Y(Y_sig) ,	// input [31:0] Y_sig
	.RESULTADO(RESULTADO_sig) ,	// output [31:0] RESULTADO_sig
	.ZERO(ZERO_sig) ,	// output  ZERO_sig
	.CONTROL(CONTROL_sig) 	// input [3:0] CONTROL_sig
);

