// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Internal Build 593 12/11/2017)
// Created on Thu Dec 21 13:26:01 2023

CLK_counter CLK_counter_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.RST_n(RST_n_sig) ,	// input  RST_n_sig
	.ENA(ENA_sig) ,	// input  ENA_sig
	.COUNT(COUNT_sig) ,	// output [n-1:0] COUNT_sig
	.TC(TC_sig) ,	// output  TC_sig
	.TC_Half(TC_Half_sig) 	// output  TC_Half_sig
);

defparam CLK_counter_inst.fin_cuenta = 50000000;
//defparam CLK_counter_inst.n = ;
