// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Internal Build 593 12/11/2017)
// Created on Thu Dec 21 13:18:10 2023

GPIO GPIO_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.ena(ena_sig) ,	// input  ena_sig
	.mem1_dout(mem1_dout_sig) ,	// input [20:0] mem1_dout_sig
	.DOUT(DOUT_sig) 	// output [20:0] DOUT_sig
);

