// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Fri Dec 15 08:56:03 2023

if_id if_id_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.RESET_N(RESET_N_sig) ,	// input  RESET_N_sig
	.PC_IF(PC_IF_sig) ,	// input [size-1:0] PC_IF_sig
	.PC_ID(PC_ID_sig) ,	// output [size-1:0] PC_ID_sig
	.dsalida_IF(dsalida_IF_sig) ,	// input [size-1:0] dsalida_IF_sig
	.dsalida_ID(dsalida_ID_sig) 	// output [size-1:0] dsalida_ID_sig
);

defparam if_id_inst.size = 32;
