// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Fri Dec 15 08:45:40 2023

mem_wb mem_wb_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.RESET_N(RESET_N_sig) ,	// input  RESET_N_sig
	.salida_ram_MEM(salida_ram_MEM_sig) ,	// input [size-1:0] salida_ram_MEM_sig
	.alu_resultado_MEM(alu_resultado_MEM_sig) ,	// input [size-1:0] alu_resultado_MEM_sig
	.wrin_MEM(wrin_MEM_sig) ,	// input [4:0] wrin_MEM_sig
	.RegWrite_MEM(RegWrite_MEM_sig) ,	// input  RegWrite_MEM_sig
	.MemtoReg_MEM(MemtoReg_MEM_sig) ,	// input  MemtoReg_MEM_sig
	.salida_ram_WB(salida_ram_WB_sig) ,	// output [size-1:0] salida_ram_WB_sig
	.alu_resultado_WB(alu_resultado_WB_sig) ,	// output [size-1:0] alu_resultado_WB_sig
	.wrin_WB(wrin_WB_sig) ,	// output [4:0] wrin_WB_sig
	.RegWrite_WB(RegWrite_WB_sig) ,	// output  RegWrite_WB_sig
	.MemtoReg_WB(MemtoReg_WB_sig) 	// output  MemtoReg_WB_sig
);

defparam mem_wb_inst.size = 32;
