// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Internal Build 593 12/11/2017)
// Created on Thu Dec 21 13:21:10 2023

memory_control memory_control_inst
(
	.clock(clock_sig) ,	// input  clock_sig
	.d_rw_memoriaRAM(d_rw_memoriaRAM_sig) ,	// output  d_rw_memoriaRAM_sig
	.d_rw(d_rw_sig) ,	// input  d_rw_sig
	.mem0_dw(mem0_dw_sig) ,	// output [31:0] mem0_dw_sig
	.mem0_dr(mem0_dr_sig) ,	// input [31:0] mem0_dr_sig
	.daddr(daddr_sig) ,	// input [10:0] daddr_sig
	.daddr_ram(daddr_ram_sig) ,	// output [9:0] daddr_ram_sig
	.ddata_w(ddata_w_sig) ,	// input [31:0] ddata_w_sig
	.ddata_r(ddata_r_sig) ,	// output [31:0] ddata_r_sig
	.mem1_ena(mem1_ena_sig) ,	// output  mem1_ena_sig
	.mem1_dout(mem1_dout_sig) 	// output [20:0] mem1_dout_sig
);

