// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Internal Build 593 12/11/2017)
// Created on Fri Dec 08 19:37:50 2023

mux_4to1 mux_4to1_inst
(
	.select(select_sig) ,	// input [1:0] select_sig
	.dato1(dato1_sig) ,	// input [31:0] dato1_sig
	.dato2(dato2_sig) ,	// input [31:0] dato2_sig
	.dato3(dato3_sig) ,	// input [31:0] dato3_sig
	.salida(salida_sig) 	// output [31:0] salida_sig
);

