// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Internal Build 593 12/11/2017)
// Created on Fri Dec 08 19:27:02 2023

RAM RAM_inst
(
	.data(data_sig) ,	// input [size-1:0] data_sig
	.wren(wren_sig) ,	// input  wren_sig
	.clock(clock_sig) ,	// input  clock_sig
	.address(address_sig) ,	// input [size-1:0] address_sig
	.salida(salida_sig) 	// output [size-1:0] salida_sig
);

defparam RAM_inst.mem_depth = 1024;
defparam RAM_inst.size = 32;
